### ISSUE TITLE
Missing flags for MMU

### ISSUE THREAD

**Issue by jrmenzel** [GerfautGE/xv6-mars#1]
The permissions in mappages() need to set PTE_D and PTE_A:

`#define PTE_A \
    (1L << 6)  ///< page has been accessed (r/w/x) since last time this bit was
               ///< cleared
#define PTE_D \
    (1L << 7)  ///< page has been written to since last time this bit
               ///< was cleared`

Then revert https://github.com/GerfautGE/xv6-mars/commit/321bb64be951c22fa8facb17762401d75a24ad35 .

With that xv6 boots on a Visionfive2 board. qemu does not seem to set these flags or trigger an interrupt on access. Spike does and also needs these flags to boot xv6 (newer Spike versions also expect Sv48 instead of Sv39).

**Comment by GerfautGE** [comment]
Thanks for your contribution ! 
The board is not with me this week but I've written this commit : 2255ef84fb9fcb55fd45b728395e96c5aef98dc7 
Could you tell me if I'm doing it right ?

**Comment by jrmenzel** [comment]
That commit works for me.
